export const ROUTES = {
  landing: '/',
  product: '/product',
  pricing: '/pricing',
  blog: '/blog',
  post: '/blog/:slug',
  help: '/help',
  feedback: '/help/feedback',
  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  terms: '/terms',
  privacy: '/privacy',
  onboarding: '/onboarding',
  app: '/app',
  orders: '/app/orders',
  products: '/app/products',
  customers: '/app/customers',
  discounts: '/app/discounts',
  marketing: '/app/marketing',
  analytics: '/app/analytics',
  settings: '/app/settings',
  notifications: '/app/settings/notifications',
  billing: '/app/settings/billing',
} as const
